### ISSUE TITLE
Cannot run the demo

### ISSUE THREAD

**Issue by wcshds** [wwwwpj/Puzzle-Pieces-Picker#2]
the error message is:
```
Error
Could not parse server response: SyntaxError: Unexpected token 'I', "Internal S"... is not valid JSON
```
![image](https://github.com/user-attachments/assets/e5c40a1b-4fdc-4dfd-ab7c-4345103b88dd)

**Comment by Pengjie-W** [comment]
Sorry, this was due to our server's GPU memory being full. After adjustments, it should be working now.

**Comment by wcshds** [comment]
> Sorry, this was due to our server's GPU memory being full. After adjustments, it should be working now.

Thanks for your quick reply! Now it works.
